export const REQUEST_CALL_GET_API_VERSION = 'REQUEST_CALL_GET_API_VERSION';
export const ON_SUCCESS_GET_API_VERSION = 'ON_SUCCESS_GET_API_VERSION';
export const REQUEST_CALL_GET_API_RESULT = 'REQUEST_CALL_GET_API_RESULT';
export const ON_SUCCESS_GET_API_RESULT = 'ON_SUCCESS_GET_API_RESULT';

export const ON_API_FAILURE = 'ON_API_FAILURE';
